# Generated by Django 2.0 on 2022-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.PositiveIntegerField()),
                ('voter', models.PositiveIntegerField()),
                ('option', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Percentages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting', models.PositiveIntegerField()),
                ('percen', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter', models.TextField()),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
