name: release

on:
  push: 
    tags:
      - '*'

jobs:
  buildTest:
    uses: egc-decide-trebujena/decide/.github/workflows/django.yml@feature/074
    secrets: 
      CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
     
  release:
    needs: buildTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
